"""Shared loaders and constants for the crab-shack tooling.

Hand-written sources:
  marketplace.yaml                        repo-level marketplace metadata
  plugins/<name>/plugin.json              Agent Plugins manifest, per-plugin source of truth
  plugins/<name>/skills/<skill>/SKILL.md  skill content, never rewritten by tooling

Every plugin is a portable Agent Plugins package: plugin.json at the plugin
root plus skills/. Claude Code is the one client that needs its own manifests,
so .claude-plugin/marketplace.json and each plugin's .claude-plugin/plugin.json
are generated by scripts/sync_manifests.py.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    raise SystemExit("error: pyyaml is required. Install with `pip install pyyaml`.")


REPO_ROOT = Path(__file__).resolve().parent.parent
PLUGINS_DIR = REPO_ROOT / "plugins"
CONFIG_PATH = REPO_ROOT / "marketplace.yaml"
SCHEMAS_DIR = REPO_ROOT / "scripts" / "schemas"

AGENT_PLUGINS_VERSION = "1.0.0"
PLUGIN_SCHEMA_URL = f"https://agent-plugins.org/schemas/{AGENT_PLUGINS_VERSION}/plugin.schema.json"
MCP_SCHEMA_URL = f"https://agent-plugins.org/schemas/{AGENT_PLUGINS_VERSION}/mcp.schema.json"
PLUGIN_SCHEMA_PATH = SCHEMAS_DIR / "agent-plugins" / AGENT_PLUGINS_VERSION / "plugin.schema.json"
MCP_SCHEMA_PATH = SCHEMAS_DIR / "agent-plugins" / AGENT_PLUGINS_VERSION / "mcp.schema.json"

CLAUDE_MARKETPLACE = Path(".claude-plugin/marketplace.json")
PLUGIN_GENERATED_FILES = (Path(".claude-plugin/plugin.json"),)

# Intersection of the Agent Skills, Agent Plugins, and Claude Code name rules:
# lowercase alphanumerics separated by single hyphens.
NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
NAME_MAX = 64
DESCRIPTION_MAX = 1024
COMPATIBILITY_MAX = 500
SEMVER_RE = re.compile(r"^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$")
FRONTMATTER_RE = re.compile(r"\A---\r?\n(.*?)\r?\n---\r?\n", re.DOTALL)


@dataclass
class Skill:
    name: str
    path: Path
    frontmatter: dict | None = None
    error: str | None = None

    @property
    def dir(self) -> Path:
        return self.path.parent


@dataclass
class Plugin:
    name: str
    dir: Path
    manifest: dict | None = None
    manifest_error: str | None = None
    skills: list[Skill] = field(default_factory=list)

    @property
    def manifest_path(self) -> Path:
        return self.dir / "plugin.json"

    @property
    def source(self) -> str:
        return f"./{self.dir.relative_to(REPO_ROOT).as_posix()}"


def rel(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def parse_frontmatter(path: Path) -> dict | None:
    text = path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        return None
    try:
        data = yaml.safe_load(match.group(1))
    except yaml.YAMLError as exc:
        raise ValueError(f"invalid YAML: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError("frontmatter must be a YAML mapping")
    return data


def load_config() -> dict:
    data = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{rel(CONFIG_PATH)} must be a YAML mapping")
    return data


def load_plugins() -> list[Plugin]:
    plugins: list[Plugin] = []
    if not PLUGINS_DIR.is_dir():
        return plugins
    for plugin_dir in sorted(p for p in PLUGINS_DIR.iterdir() if p.is_dir()):
        plugin = Plugin(name=plugin_dir.name, dir=plugin_dir)
        if plugin.manifest_path.exists():
            try:
                manifest = json.loads(plugin.manifest_path.read_text(encoding="utf-8"))
                if isinstance(manifest, dict):
                    plugin.manifest = manifest
                else:
                    plugin.manifest_error = "plugin.json must be a JSON object"
            except json.JSONDecodeError as exc:
                plugin.manifest_error = f"invalid JSON: {exc}"
        else:
            plugin.manifest_error = "plugin.json not found"
        for skill_md in sorted((plugin_dir / "skills").glob("*/SKILL.md")):
            skill = Skill(name=skill_md.parent.name, path=skill_md)
            try:
                skill.frontmatter = parse_frontmatter(skill_md)
            except ValueError as exc:
                skill.error = str(exc)
            plugin.skills.append(skill)
        plugins.append(plugin)
    return plugins


def render_json(obj: object) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"
